import type { Config } from 'tailwindcss';

export default {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        primary: '#4144e5',
        'primary-container': '#5c61ff',
        'primary-fixed': '#e1e0ff',
        'primary-fixed-dim': '#c0c1ff',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#04006d',
        'on-primary-fixed-variant': '#2625cf',
        'on-primary-container': '#ffffff',
        'inverse-primary': '#c0c1ff',
        'surface-tint': '#4246e6',
        secondary: '#006d37',
        'secondary-container': '#6bfe9c',
        'secondary-fixed': '#6bfe9c',
        'secondary-fixed-dim': '#4ae183',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#00743a',
        'on-secondary-fixed': '#00210c',
        'on-secondary-fixed-variant': '#005228',
        tertiary: '#b2261b',
        'tertiary-container': '#d53f31',
        'tertiary-fixed': '#ffdad5',
        'tertiary-fixed-dim': '#ffb4a9',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fffeff',
        'on-tertiary-fixed': '#410000',
        'on-tertiary-fixed-variant': '#910807',
        background: '#f9f9fc',
        surface: '#f9f9fc',
        'surface-bright': '#f9f9fc',
        'surface-dim': '#dadadc',
        'surface-variant': '#e2e2e5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f6',
        'surface-container': '#eeeef0',
        'surface-container-high': '#e8e8ea',
        'surface-container-highest': '#e2e2e5',
        'inverse-surface': '#2f3133',
        'inverse-on-surface': '#f0f0f3',
        'on-surface': '#1a1c1e',
        'on-surface-variant': '#454555',
        'on-background': '#1a1c1e',
        outline: '#767587',
        'outline-variant': '#c6c4d8',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        headline: ['Manrope', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        card: '16px',
        button: '12px',
        input: '10px',
        progress: '999px',
      },
      boxShadow: {
        card: '0 2px 32px rgba(0, 0, 0, 0.04)',
        elevated: '0 4px 48px rgba(0, 0, 0, 0.06)',
      },
    },
  },
  plugins: [],
} satisfies Config;
